"""add password reset fields to members

Revision ID: 0a5112e12538
Revises: 15e8f88ef4d4
Create Date: 2025-11-25 18:55:35.753836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5112e12538'
down_revision: Union[str, Sequence[str], None] = '15e8f88ef4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('reset_token_expires', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'reset_token_expires')
    op.drop_column('members', 'reset_token')
    # ### end Alembic commands ###
