"""add request_id and duration_ms to audit_logs

Revision ID: 4ae4ad4ae996
Revises: 20260102_file_path
Create Date: 2026-01-02 23:15:44.679310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae4ad4ae996'
down_revision: Union[str, Sequence[str], None] = '20260102_file_path'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'duration_ms')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
