"""sync_models

Revision ID: f556d4c228a4
Revises: 2aa86f951f6e
Create Date: 2026-01-02 17:32:33.838682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f556d4c228a4'
down_revision: Union[str, Sequence[str], None] = '2aa86f951f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_app_logs_created_at'), 'app_logs', ['created_at'], unique=False)
    op.drop_column('app_logs', 'file_path')
    
    # Drop existing file_id column and recreate as UUID
    op.drop_column('attachments', 'file_id')
    op.add_column('attachments', sa.Column('file_id', sa.UUID(), nullable=True))
    
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_column('audit_logs', 'file_path')
    op.create_index(op.f('ix_error_logs_created_at'), 'error_logs', ['created_at'], unique=False)
    op.drop_column('error_logs', 'file_path')
    op.create_index(op.f('ix_performance_logs_created_at'), 'performance_logs', ['created_at'], unique=False)
    op.drop_column('performance_logs', 'file_path')
    op.create_foreign_key(None, 'performance_records', 'admins', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.drop_column('system_logs', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_constraint(None, 'performance_records', type_='foreignkey')
    op.add_column('performance_logs', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_performance_logs_created_at'), table_name='performance_logs')
    op.add_column('error_logs', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_error_logs_created_at'), table_name='error_logs')
    op.add_column('audit_logs', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    
    # Recreate file_id as VARCHAR
    op.drop_column('attachments', 'file_id')
    op.add_column('attachments', sa.Column('file_id', sa.VARCHAR(length=255), nullable=True))
    
    op.add_column('app_logs', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_app_logs_created_at'), table_name='app_logs')
    # ### end Alembic commands ###
