import os
import sys
from datetime import datetime

def generate_prd_template(feature_name):
    timestamp = datetime.now().strftime("%Y-%m-%d")
    template = f"""# PRD: {feature_name}

**版本**: v1.0
**日期**: {timestamp}
**状态**: 草案 (Draft)

---

## 1. 业务目标与愿景 (Vision)
[在此描述该功能解决了分析师的什么核心痛点]

- **目标**: 
- **主要指标**: Accuracy >= 75%, P95 < 3s

## 2. 用户故事 (User Stories)
> **作为** [角色], **我想要** [动作], **以便** [收益]。

- **US-001**: 
- **术语检查**: 是否遵循 `dev-terminology`？(如：使用 Analyst 而非 User)

## 3. 功能详情 (Functional Requirements)

### 3.1 AI/RAG 检索逻辑
- **数据源**: 
- **检索类型**: Hybrid (Vector + Keyword)
- **Top-K**: 5
- **Prompt 关键点**: 

### 3.2 UI/UX 体验 (Premium Design)
- **视觉风格**: 遵循 `dev-frontend_patterns` (渐变、软阴影、毛玻璃)
- **微互动**: 定义加载中及反馈动效

### 3.3 库与组件兼容性
- **第三方库**: (如：recharts, pdfjs)
- **兼容性评估**: 参考 `dev-libs_compatibility`

### 3.4 国际化 (i18n)
- **英语/法语**: 

## 4. 验收标准 (Acceptance Criteria)
- [ ] **功能路径**: 
- [ ] **AI 检索**: 必须提供包含文档标题和页码的引用。
- [ ] **性能**: 并发 50 人时响应时间 < 3s。
- [ ] **边界处理**: 搜索无结果时应返回优雅的提示信息。
- [ ] **术语/UI 校验**: 命名及样式符合 Skill 规范。

## 5. 技术注解 (Technical Notes)
- **API 端点**: 
- **依赖 Skill**: dev-testing_standards, dev-frontend_patterns

---
*Generated by dev-prd automation tool.*
"""
    return template

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_prd.py <FeatureName>")
        sys.exit(1)
    
    feature = sys.argv[1]
    content = generate_prd_template(feature)
    
    # 默认保存在 docs/requirements/ 目录下
    output_dir = "docs/requirements"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    file_path = os.path.join(output_dir, f"prd_{feature.lower().replace(' ', '_')}.md")
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    print(f"✅ PRD template generated at: {file_path}")
